version: "3.7"
services:
  user-service-database:
    container_name: "user-service-database"
    restart: always
    image: postgres:alpine
    environment:
      - POSTGRES_DB=ntp-user-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  user-service:
    container_name: "user-service"
    build:
      context: user-service/
      dockerfile: Dockerfile
    environment:
      - JWT_SIGNING_KEY=signing_key
      - POSTGRES_DB=ntp-user-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=user-service-database
    depends_on:
      - user-service-database

  drink-service-database:
    container_name: "drink-service-database"
    restart: always
    image: postgres:alpine
    environment:
      - POSTGRES_DB=ntp-drink-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  drink-service:
    container_name: "drink-service"
    build:
      context: drink-service/
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=ntp-drink-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=drink-service-database
      - USER_SERVICE_HOST=user-service
      - PURCHASE_SERVICE_HOST=purchase-service
    depends_on:
      - drink-service-database

  comment-service-database:
    container_name: "comment-service-database"
    image: mongo
    restart: always
    environment:
      - MONGO_HOST=comment-service-database
      - MONGO_DB=ntp-comment-service

  comment-service:
    container_name: "comment-service"
    build:
      context: comment-service/
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=ntp-comment-service
      - MONGO_HOST=comment-service-database
      - PURCHASE_SERVICE_HOST=purchase-service
      - USER_SERVICE_HOST=user-service
    depends_on:
      - comment-service-database

  purchase-service-database:
    container_name: "purchase-service-database"
    restart: always
    image: postgres:alpine
    environment:
      - POSTGRES_DB=ntp-purchase-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  purchase-service:
    container_name: "purchase-service"
    build:
      context: purchase-service/
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=ntp-purchase-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=purchase-service-database

  frontend:
    container_name: frontend
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - "9090:80"

  api-gateway:
    container_name: api-gateway
    build:
      context: nginx/docker/
      dockerfile: Dockerfile
    ports:
      - "9999:80"
